---
- name: repmgr | ensure repmgr pid file directory
  file:
    path: /run/repmgr/
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    mode: '0740'
    state: directory

- name: repmgr | create repmgr conf dir
  file:
    path: "{{ repmgr_conf_dir }}"
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    mode: '0740'
    state: directory
    recurse: true
  when: ansible_os_family != Debian

- name: repmgr | create repmgr conf
  template:
    src: repmgr.conf.j2
    dest: "{{ repmgr_conf_dir }}/{{ repmgr_conf_file }}"
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    mode: '0740'
  register: repmgr_conf
