---
- name: repmgr | ensure repmgr pid file directory
  file:
    path: /run/repmgr/
    mode: 0770
    owner: "{{ repmgr_postgres_admin_user }}"
    group: "{{ repmgr_postgres_admin_user_group }}"
    state: directory

- name: repmgr | create repmgr conf dir
  file:
    path: "{{ repmgr_conf_dir }}"
    state: directory
    recurse: yes

- name: repmgr | create repmgr conf
  template:
    src: repmgr.conf.j2
    dest: "{{ repmgr_conf_dir }}/{{ repmgr_conf_file }}"
  register: repmgr_conf
