---
- name: repmgr | ensure repmgr pid file directory
  file:
    path: /run/repmgr/
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    mode: '0740'
    state: directory

- name: repmgr | create repmgr conf
  template:
    src: repmgr.conf.j2
    dest: "{{ repmgr_conf_dir }}/{{ repmgr_conf_file }}"
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    mode: '0740'
  register: repmgr_conf

- name: repmgr | add sudo capability to postgres user
  template:
    src: etc/sudoers.d/postgres.j2
    dest: /etc/sudoers.d/postgres
    owner: root
    group: root
    mode: '0440'
