---
- name: repmgr | ensure repmgr pid file directory
  file:
    path: /run/repmgr/
    owner: "root"
    group: "root"
    mode: '0740'
    state: directory

- name: repmgr | create repmgr conf dir
  file:
    path: "{{ repmgr_conf_dir }}"
    owner: "root"
    group: "root"
    mode: '0740'
    state: directory
    recurse: true

- name: repmgr | create repmgr conf
  template:
    src: repmgr.conf.j2
    dest: "{{ repmgr_conf_dir }}/{{ repmgr_conf_file }}"
    owner: "root"
    group: "root"
    mode: '0740'
  register: repmgr_conf
