---
- name: Ensure PostgreSQL packages are installed.
  yum:
    name: "{{ postgresql_server_package }}"
    state: present
    enablerepo: "{{ postgres_repo }}"
    exclude: python-unversioned-command
  when: repmgr_install_postgresql|bool

- name: repmgr | install repmgr gpg key
  copy:
    dest: "{{ repmgr_gpg_file }}"
    content: "{{ repmgr_gpg_key }}"
    owner: "root"
    group: "root"
    mode: '0740'
  when: repmgr_install_gpg_key

- name: repmgr | install repmgr yum repository
  yum_repository:
    name: "repmgr_{{ postgres_release }}"
    description: 2ndquadrant yum repo
    baseurl: "{{ repmgr_repository }}"
    gpgkey: "file:///{{ repmgr_gpg_file }}"
  when: repmgr_install_repository

- name: repmgr | install repmgr
  yum:
    name: "{{ repmgr_package }}"
    state: present
