---
# PostGreSQL is Managed by anxs.postgresql

- name: repmgr | install repmgr repository
  ansible.builtin.apt_repository:
    filename: "repmgr_2ndquadrant"
    repo: "{{ repmgr_repository }}"
    state: present
  when: repmgr_install_repository|bool

- name: Download and install GPG key
  ansible.builtin.apt_key:
    state: present
    url: https://dl.2ndquadrant.com/gpg-key.asc
  when: repmgr_install_repository|bool

- name: repmgr | install repmgr
  ansible.builtin.package:
    name: "{{ repmgr_package }}"
    state: present

- name: repmgr | configure /etc/default/repmgrd
  ansible.builtin.lineinfile:
    path: /etc/default/repmgrd
    regexp: "^#?{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ repmgr_repmgrd_conf }}"