---
- include: install.yml

- include: configure.yml

- include: bootstrap.yml
  when: repmgr_bootstrap|bool

- include: verify_cluster.yml
  when: repmgr_register_master|bool or repmgr_register_standby|bool or repmgr_clone_master|bool

- include: register_master.yml
  when: repmgr_register_master|bool

- include: clone_standby.yml
  when: 
    - repmgr_clone_standby|bool

- include: register_standby.yml
  when: 
    - repmgr_register_standby|bool
    - repmgr_clone_standby|bool
