---

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"

- include: "install-{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'RedHat'

- include: configure.yml
  when: not repmgr_install_only|bool

- include: bootstrap.yml
  when:
    - repmgr_bootstrap|bool
    - not repmgr_install_only|bool

- include: verify_cluster.yml
  when:
    - repmgr_register_master|bool or repmgr_register_standby|bool or repmgr_clone_standby|bool
    - not repmgr_install_only|bool

- include: register_master.yml
  when:
    - repmgr_register_master|bool
    - not repmgr_install_only|bool

- include: clone_standby.yml
  when:
    - repmgr_clone_standby|bool
    - not repmgr_install_only|bool

- include: register_standby.yml
  when:
    - repmgr_register_standby|bool
    - not repmgr_install_only|bool
