---
- include: postgresql_install.yml
  when: repmgr_install_postgresql|bool

- include: install.yml

- include: configure.yml
  when: not repmgr_install_only|bool

- include: bootstrap.yml
  when:
    - repmgr_bootstrap|bool
    - not repmgr_install_only|bool

- include: verify_cluster.yml
  when:
    - repmgr_register_master|bool or repmgr_register_standby|bool or repmgr_clone_master|bool
    - not repmgr_install_only|bool

- include: register_master.yml
  when:
    - repmgr_register_master|bool
    - not repmgr_install_only|bool

- include: clone_standby.yml
  when:
    - repmgr_clone_standby|bool
    - not repmgr_install_only|bool

- include: register_standby.yml
  when:
    - repmgr_register_standby|bool
    - not repmgr_install_only|bool
