---
- name: repmgr | verify node status
  shell: "/usr/pgsql-{{ postgres_release}}/bin/repmgr -f {{ repmgr_conf_dir }}/{{ repmgr_conf_file }} node check"
  args:
    warn: false
  changed_when: false
  register: result
  ignore_errors: true
  become: yes
  become_user: "{{ repmgr_postgres_admin_user }}"

